isProd: true
name: "notion"
authUrl: "https://api.notion.com/v1/oauth/authorize"
tokenUrl: "https://api.notion.com/v1/oauth/token"
userInfoUrl: "https://api.notion.com/v1/users/me"
scopes:
  "": ""
additionalRequiredAuthUrlParams:
  "owner": "user"
additionalHeaders:
  "Notion-Version": "2022-06-28"
authTokenRequestUrlencoded: false
refreshTokenAuthHeader: true